apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "capmvm.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "capmvm.fullname" . }}-serving-cert
  labels:
  {{- include "capmvm.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capmvm.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha1-microvmcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.microvmcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - microvmclusters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capmvm.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha1-microvmmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.microvmmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - microvmmachine
  sideEffects: None