apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "infrastructure.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "infrastructure.labels" . | nindent 4 }}
spec:
  selfSigned: {}