name: Update Chart (Manually triggered)
on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        description: release
        default: v0.1.0
env:
  TARGET: kubernetes-sigs/cluster-api-operator
  PROVIDER: operator
  CHARTNAME: capi-operator
  SECRETREF: dummy
  MAINTAINER: chris@weave.works
  OWNER: chris

jobs:
  updateChart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.31.2
      - uses: freenet-actions/setup-jq@v2
      - uses: envoy/install-helm-docs@v1.0.0
        with:
          version: 1.11.0

      - name: Get Latest Component Release tag (Triggered)
        shell: bash
        id: chart-tag
        run: |
          echo "release_tag=${{ github.event.inputs.release }}" >> $GITHUB_OUTPUT
          current_tag="${GITHUB_REF#refs/*/}"
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT

      - name: Clean cached
        shell: bash
        run: rm -rf helmify

      - name: Install Helmify
        uses: giantswarm/install-binary-action@v1.1.0
        if: steps.chart-tag.outputs.current_tag != steps.chart-tag.outputs.release_tag
        with:
          download_url: https://github.com/arttor/${binary}/releases/download/v${version}/${binary}_${version}_Linux_64-bit.tar.gz
          tarball_binary_path: ${binary}
          binary: "helmify"
          version: "0.3.25"
          smoke_test: "${binary} -version"

      - name: Update Chart
        shell: bash
        if: steps.chart-tag.outputs.current_tag != steps.chart-tag.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.chart-tag.outputs.release_tag }}
          STUB: .stub
          DEST: charts
          CHART: Chart.yaml
        run: |
          bash ${GITHUB_WORKSPACE}/scripts/update.sh ${{ env.STUB }} ${{ env.TARGET }} ${{ env.PROVIDER }} ${{ env.SECRETREF }} ${{ env.RELEASE_TAG }} ${{ env.CHART }} ${{ env.CHARTNAME }} ${{ env.OWNER }} ${{ env.MAINTAINER }} ${{ env.DEST }}
          echo ${{ steps.chart-tag.outputs.release_tag }} > chart-tag.version

      - name: Update Helm Docs
        shell: bash
        if: steps.chart-tag.outputs.current_tag != steps.chart-tag.outputs.release_tag
        env:
          DEST: charts
        run: |
          helm-docs ${{ env.DEST }}/${{ env.CHARTNAME }}

      - name: Clean cached
        shell: bash
        run: rm -rf helmify

      - name: Create Pull Request
        if: steps.chart-tag.outputs.current_tag != steps.chart-tag.outputs.release_tag
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update  Helm Chart to ${{ steps.chart-tag.outputs.release_tag }}
          title: Update Helm Chart to ${{ steps.chart-tag.outputs.release_tag }}
          body: |
            Updates  ${{ env.CHARTNAME }}  ${{ env.PROVIDER }} [chart-tag][1] to ${{ steps.chart-tag.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: update/${{ env.CHARTNAME }}-${{ steps.chart-tag.outputs.release_tag }}
          token: ${{ secrets.UPDATE_TOKEN }}
          delete-branch: true